### ISSUE TITLE
Ready TOC and TOCController for indigo replacement

### ISSUE THREAD

**Issue by musangowope** [laws-africa/la-web-components#35]
- [ ] create custom event `itemRendered` that is emit with item data when la-toc-item is rendered
- [ ] add sb story demoing `itemRendered`
- [ ] Write basic test for `itemRendered`
- [ ] update `item` prop of `la-toc-item` to possibly have `selected` it data shaped i.e.
```
{
  title: "Lorem",
  children: [],
  selected: false
}
```
use `selected` to conditionally append CSS class `active` to of `la-toc-item .content__action`

**Comment by longhotsummer** [comment]
I think we can close this?

**Comment by musangowope** [comment]
yep
